-- Show a tuned sink in GNOME only while its device is actually connected.
--
-- Each external device has its own filter chain, generated by
-- gen-external-chains.py, so GNOME can list real device names and do the
-- switching itself. But those chains are static config: they exist whether or
-- not the device is plugged in or paired up. Left visible, a sink for an absent
-- device is worse than clutter -- selecting it sends audio to a chain whose
-- target does not resolve, and PipeWire then routes that to the default sink,
-- which is another tuned sink. The stream would be processed twice, by two
-- chains.
--
-- Hiding them also buys the thing the design otherwise could not have: chains
-- can be generated once for every device you own, and connecting any of them
-- later makes its entry appear on its own, with no regeneration and no restart.
--
-- The device each chain belongs to is named by speaker-dsp.device, written in
-- by the generator, rather than inferred from the sink's name.

log = Log.open_topic ("s-hide-absent-tuned")

tuned_om = ObjectManager {
  Interest { type = "node",
    Constraint { "speaker-dsp.device", "is-present" },
  }
}

sinks_om = ObjectManager {
  Interest { type = "node", Constraint { "media.class", "=", "Audio/Sink" } }
}

clients_om = ObjectManager { Interest { type = "client" } }

local function is_gvc_mixer_client (client)
  local props = client["properties"]
  return props ~= nil
      and props["client.api"] == "pipewire-pulse"
      and props["application.id"] == "org.gnome.VolumeControl"
      and props["application.icon-name"] == "multimedia-volume-control"
end

local function device_present (name)
  for node in sinks_om:iterate () do
    if node.properties["node.name"] == name then return true end
  end
  return false
end

local function apply ()
  for client in clients_om:iterate () do
    if is_gvc_mixer_client (client) then
      local cid = client["bound-id"]
      for node in tuned_om:iterate () do
        local nid = node["bound-id"]
        local dev = node.properties["speaker-dsp.device"]
        if nid ~= nil and cid ~= nil and dev ~= nil then
          -- "-" hides it from this client; restoring the default permissions
          -- brings it back when the device returns.
          local perm = device_present (dev) and "rwxm" or "-"
          pcall (function ()
            client:update_permissions { [nid] = perm }
          end)
        end
      end
    end
  end
end

clients_om:connect ("object-added", function () apply () end)
tuned_om:connect ("object-added", function () apply () end)
sinks_om:connect ("object-added", function () apply () end)
sinks_om:connect ("object-removed", function () apply () end)

clients_om:activate ()
tuned_om:activate ()
sinks_om:activate ()
